[project]
name = "chainvoice"
requirements = []

[contracts.profiles]
path = "contracts/profiles.clar"
clarity_version = 2
epoch = 2.5

[contracts.messages]
path = "contracts/messages.clar"
clarity_version = 2
epoch = 2.5
